### ISSUE TITLE
skbio.stats.composition - ancom runtime warning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by handibles** [biocore/scikit-bio#1524] opened 2017-07-18 14:15 UTC
Firstly, apologies if this is not the place for more community-orientated support, but I couldn't see an alternative channel.

   My OTU data has come through QIIME and phyloseq, exported to text and then into python.

   I'm using multiplicative_replacement on an OTU table, then testing with defaults in ancom over two uneven-sized groups (10,4). When run, I receive a warning but am unsure if I should be concerned about it, as I still receive the expected output.

   Multiplicative replacement should remove 0 values from my OTU table - is this an issue with tiny pseudocounts reverting to zero? Or something more fundamental? 

```
# imported pandas, skbio, scipy
otu_rep = mult_rep(otu)
index = otu.index.values
columns = otu.columns.values
otu_rep = pd.DataFrame(otu_rep,index=index,columns=columns)
groupA=pd.Series(['1','1','1','1','1','1','1','1','1','1','2','2','2','2'],index=[index])
resultsA = ancom(otu_rep,groupA)

**/home/cith/miniconda3/lib/python3.6/site-packages/scipy/stats/stats.py:2968: RuntimeWarning: invalid value encountered in double_scalars
  f = msb / msw**
```

thanks for your time.

**Comment by handibles** [comment] 2017-07-18 14:36
Update: tested ancom on this set using a different pseudocount strategy (+1 all observations) and received the same warning so assume not an issue with mult_repl. Is this an issue with ancom or with the data I'm supplying? 
If the latter, any suggestions as to the cause?

**Comment by mortonjt** [comment] 2017-07-18 14:49
I'm not exactly sure what the problem here is - is it possible to attach the otu table?  Or even better, reproduce this error with a smaller dataset?

**Comment by handibles** [comment] 2017-07-18 15:53
Thanks @mortonjt .  I should have mentioned also that I've tried it with two different datasets and receive the same error in either. Small subset OTU table supplied provides the error.

 
[h_curtailed.txt](https://github.com/biocore/scikit-bio/files/1156462/h_curtailed.txt)

**Comment by mortonjt** [comment] 2017-07-18 16:42
I'm confused ... the otu table attached has 100 rows, but the grouping that you specified only has 14.  What are the exact commands that you used that generated this error?

**Comment by handibles** [comment] 2017-07-18 17:33
apologies, I subsetted the original OTU table to 100 taxa * 10 samples.
 I've attached the original OTU table which produces the error at top directly, exported from a phyloseq object using the command: 
`write.table(otu_table(phylo),'phylo_table.txt',sep='\t')`
Ive also reproduced the code used in the attached script.


[phylo_ancom_test_script.txt](https://github.com/biocore/scikit-bio/files/1156793/phylo_ancom_test_script.txt)

[phylo_table.txt](https://github.com/biocore/scikit-bio/files/1156779/phylo_table.txt)

**Comment by handibles** [comment] 2017-07-24 13:22
Update: I've reproduced this error on a two biolinux (ubuntu 14.04 & 16.04) and one mint (version?) distro to try rule out something funky in my workstation setup. 

Could it be the layout  of the phylo_table.txt (above) thats causing the error? Is it an error I should be concerned about?

**Comment by mortonjt** [comment] 2017-07-24 15:40
Can you run the following for your script?

```
python -W error phylo_ancom_test_script.py
```

I looked at your results -- it looks like it is behaving as expected.  But it would be nice to see what traceback you get just as a sanity check.

**Comment by handibles** [comment] 2017-07-26 14:48
Thankee kindly. Behaving as expected -  in so much as it gives legible, sensible outputs?

**Python >3:** - calling `python3.4 -W error '/home/eri/Downloads/phylo_ancom_test_script.py'`
throws:
```
Traceback (most recent call last):
  File "/home/eri/Downloads/phylo_ancom_test_script.py", line 6, in <module>
    import skbio.stats.composition
  File "/usr/local/lib/python3.4/dist-packages/skbio/__init__.py", line 10, in <module>
    from skbio.util import TestRunner
  File "/usr/local/lib/python3.4/dist-packages/skbio/util/__init__.py", line 58, in <module>
    from ._testing import (get_data_path, TestRunner,
  File "/usr/local/lib/python3.4/dist-packages/skbio/util/_testing.py", line 13, in <module>
    import nose
  File "/usr/local/lib/python3.4/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/local/lib/python3.4/dist-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/usr/local/lib/python3.4/dist-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/usr/local/lib/python3.4/dist-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
  File "/usr/lib/python3.4/imp.py", line 32, in <module>
    PendingDeprecationWarning)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 13, in <module>
    import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
  File "/usr/lib/python3.4/imp.py", line 32, in <module>
    PendingDeprecationWarning)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Original exception was:
Traceback (most recent call last):
  File "/home/eri/Downloads/phylo_ancom_test_script.py", line 6, in <module>
    import skbio.stats.composition
  File "/usr/local/lib/python3.4/dist-packages/skbio/__init__.py", line 10, in <module>
    from skbio.util import TestRunner
  File "/usr/local/lib/python3.4/dist-packages/skbio/util/__init__.py", line 58, in <module>
    from ._testing import (get_data_path, TestRunner,
  File "/usr/local/lib/python3.4/dist-packages/skbio/util/_testing.py", line 13, in <module>
    import nose
  File "/usr/local/lib/python3.4/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/local/lib/python3.4/dist-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/usr/local/lib/python3.4/dist-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/usr/local/lib/python3.4/dist-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
  File "/usr/lib/python3.4/imp.py", line 32, in <module>
    PendingDeprecationWarning)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```



**Python <3:** `python` &  `python2.7 -W error '/home/eri/Downloads/phylo_ancom_test_script.py'`
throw the following:
 ```
Traceback (most recent call last):
  File "/home/eri/Downloads/phylo_ancom_test_script.py", line 6, in <module>
    import skbio.stats.composition
  File "/usr/local/lib/python2.7/dist-packages/skbio/__init__.py", line 15, in <module>
    import skbio.io
  File "/usr/local/lib/python2.7/dist-packages/skbio/io/__init__.py", line 309, in <module>
    import_module('skbio.io.clustal')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/skbio/io/clustal.py", line 123, in <module>
    from skbio.alignment import Alignment
  File "/usr/local/lib/python2.7/dist-packages/skbio/alignment/__init__.py", line 230, in <module>
    from ._alignment import Alignment, SequenceCollection, StockholmAlignment
  File "/usr/local/lib/python2.7/dist-packages/skbio/alignment/_alignment.py", line 21, in <module>
    from skbio.stats.distance import DistanceMatrix
  File "/usr/local/lib/python2.7/dist-packages/skbio/stats/distance/__init__.py", line 193, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/usr/local/lib/python2.7/dist-packages/skbio/stats/distance/_base.py", line 17, in <module>
    from IPython.core.pylabtools import print_figure
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/magic.py", line 22, in <module>
    from IPython.core import oinspect
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/oinspect.py", line 48, in <module>
    from pygments.lexers import PythonLexer
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 20, in <module>
    from pygments.plugin import find_plugin_lexers
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 39, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2535, in activate
    declare_namespace(pkg)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2109, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2042, in _handle_ns
    loader = importer.find_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
ImportWarning: Not importing directory '/usr/local/lib/python2.7/dist-packages/mpl_toolkits': missing __init__.py
```

**Comment by mortonjt** [comment] 2017-07-26 17:25
@handibles I found the problem -- and it looks like it is a problem with your table, rather than the actual code.

The way that ANCOM works is that it computes all pairwise log-ratios.  In your particular case, OTUs 0 and 2 have the exact same proportions.

```python
In [6]: otu_rep.iloc[:, 0] / otu_rep.iloc[:, 2] 
Out[6]: 
G01     1.0
G20     1.0
G37     1.0
G40     1.0
G43     1.0
G49     1.0
G54     1.0
G64     1.0
G65     1.0
G68     1.0
SG01    1.0
SG20    1.0
SG37    1.0
SG65    1.0
dtype: float64 
```
Take a log of this, you end with the following

```
In [9]: np.log(otu_rep.iloc[:, 0] / otu_rep.iloc[:, 2] )
Out[9]: 
G01     0.0
G20     0.0
G37     0.0
G40     0.0
G43     0.0
G49     0.0
G54     0.0
G64     0.0
G65     0.0
G68     0.0
SG01    0.0
SG20    0.0
SG37    0.0
SG65    0.0
dtype: float64
```
ANCOM will compute a statistical test on this -- no statistical test will return a sane answer for a vector of zeros.  In this case -- the t-test will actually throw a nan.

That being said, this won't actually impact the downstream results, so this will not be a problem.

**Comment by handibles** [comment] 2017-07-26 18:10
Wow, thats awkward but kind of neat! Thanks for taking the time to clear it up. 

Apologies for calling out such an incidental issue tho. Is there an alternative Q/A resource for SKB-Ancom & co?

_Sent from my Samsung GT-I9505 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mortonjt** [comment] 2017-08-07 19:03
Since ANCOM is part of scikit-bio - we will continue to address issues with the code here.

If you have statistical questions concerning the tool, I'd consider contacting the [Shyamal Peddada](https://www.niehs.nih.gov/research/atniehs/labs/bb/staff/peddada/index.cfm)

**Comment by mortonjt** [comment] 2017-08-07 19:14
It looks like this problem is solved, so we'll close this issue

**Closed** 2017-08-07 19:14 UTC
