### ISSUE TITLE
Locale dependent tests

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#1262] opened 2016-02-03 22:12 UTC
There are some test errors when the system's locale is not C or en_US. This command reproduces the failures: `LANG="es_ES.UTF-8" make test`. Changing it to `LANG="en_US.UTF-8" make test` solves the problems. 

```
ERROR: test_genbank_to_dna (skbio.io.format.tests.test_genbank.ReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 371, in test_genbank_to_dna
    obs = _genbank_to_dna(self.multi_fp, seq_num=i+1)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 329, in _genbank_to_dna
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '29-AUG-2010' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_genbank_to_generator (skbio.io.format.tests.test_genbank.ReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 348, in test_genbank_to_generator
    for i, obs in enumerate(_genbank_to_generator(self.multi_fp)):
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 979, in wrapped_reader
    for item in reader_function(fhs[-1], **kwargs):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 317, in _genbank_to_generator
    for record in _parse_genbanks(fh):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '29-AUG-2010' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_genbank_to_rna (skbio.io.format.tests.test_genbank.ReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 363, in test_genbank_to_rna
    obs = _genbank_to_rna(self.single_rna_fp)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 335, in _genbank_to_rna
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '26-APR-1993' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_genbank_to_sequence (skbio.io.format.tests.test_genbank.ReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 356, in test_genbank_to_sequence
    obs = _genbank_to_sequence(self.multi_fp, seq_num=i+1)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 323, in _genbank_to_sequence
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '29-AUG-2010' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_parse_locus (skbio.io.format.tests.test_genbank.ReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 247, in test_parse_locus
    self.assertEqual(_parse_locus(serialized), parsed)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '18-DEC-2001' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_roundtrip_dna (skbio.io.format.tests.test_genbank.RoundtripTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 470, in test_roundtrip_dna
    _dna_to_genbank(_genbank_to_dna(self.single_rna_fp), fh)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 329, in _genbank_to_dna
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '26-APR-1993' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_roundtrip_generator (skbio.io.format.tests.test_genbank.RoundtripTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 448, in test_roundtrip_generator
    _generator_to_genbank(_genbank_to_generator(self.multi_fp), fh)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 1054, in wrapped_writer
    writer_function(obj, fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 347, in _generator_to_genbank
    for obj_i in obj:
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 979, in wrapped_reader
    for item in reader_function(fhs[-1], **kwargs):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 317, in _genbank_to_generator
    for record in _parse_genbanks(fh):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '29-AUG-2010' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_roundtrip_rna (skbio.io.format.tests.test_genbank.RoundtripTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 459, in test_roundtrip_rna
    _rna_to_genbank(_genbank_to_rna(self.single_rna_fp), fh)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 335, in _genbank_to_rna
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '26-APR-1993' does not match format '%d-%b-%Y'

======================================================================
ERROR: test_roundtrip_sequence (skbio.io.format.tests.test_genbank.RoundtripTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 492, in test_roundtrip_sequence
    _sequence_to_genbank(_genbank_to_sequence(self.single_rna_fp), fh)
  File "/home/jorge/code/forks/bipy/skbio/io/registry.py", line 969, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 323, in _genbank_to_sequence
    record = _get_nth_sequence(_parse_genbanks(fh), seq_num)
  File "/home/jorge/code/forks/bipy/skbio/io/format/_base.py", line 110, in _get_nth_sequence
    for i, seq in zip(range(1, seq_num + 1), generator):
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 397, in _parse_genbanks
    yield _parse_single_genbank(data_chunks)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 421, in _parse_single_genbank
    parsed = parser(section)
  File "/home/jorge/code/forks/bipy/skbio/io/format/genbank.py", line 513, in _parse_locus
    res['date'] = datetime.strptime(res['date'], _TIME_FORMAT)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 507, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data '26-APR-1993' does not match format '%d-%b-%Y'

======================================================================
ERROR: Failure: ValueError ('/home/jorge/code/forks/bipy/skbio/parse/__init__.py/__init__.pyc' is not a package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/jorge/anaconda/envs/py3/lib/python3.4/imp.py", line 210, in load_package
    raise ValueError('{!r} is not a package'.format(path))
ValueError: '/home/jorge/code/forks/bipy/skbio/parse/__init__.py/__init__.pyc' is not a package

======================================================================
FAIL: test_positives (skbio.io.format.tests.test_genbank.SnifferTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 51, in test_positives
    self.assertEqual(_genbank_sniffer(fp), (True, {}))
AssertionError: Tuples differ: (False, {}) != (True, {})

First differing element 0:
False
True

- (False, {})
+ (True, {})

======================================================================
FAIL: test_dna_protein_to_genbank (skbio.io.format.tests.test_genbank.WriterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 429, in test_dna_protein_to_genbank
    self.assertEqual(obs, exp)
AssertionError: 'LOCU[1006 chars] 29-AGO-2010\nDEFINITION  Uncultured Xylanimon[584 chars]//\n' != 'LOCU[1006 chars] 29-AUG-2010\nDEFINITION  Uncultured Xylanimon[584 chars]//\n'
Diff is 1875 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_rna_to_genbank (skbio.io.format.tests.test_genbank.WriterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 442, in test_rna_to_genbank
    self.assertEqual(obs, exp)
AssertionError: 'LOCU[47 chars] 26-ABR-1993\nDEFINITION  alkaline phosphatase[1066 chars]//\n' != 'LOCU[47 chars] 26-APR-1993\nDEFINITION  alkaline phosphatase[1066 chars]//\n'
Diff is 1380 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_sequence_to_genbank (skbio.io.format.tests.test_genbank.WriterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 414, in test_sequence_to_genbank
    self.assertEqual(obs, exp)
AssertionError: 'LOCU[1006 chars] 29-AGO-2010\nDEFINITION  Uncultured Xylanimon[584 chars]//\n' != 'LOCU[1006 chars] 29-AUG-2010\nDEFINITION  Uncultured Xylanimon[584 chars]//\n'
Diff is 1875 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_serialize_locus (skbio.io.format.tests.test_genbank.WriterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jorge/code/forks/bipy/skbio/io/format/tests/test_genbank.py", line 389, in test_serialize_locus
    _serialize_locus('LOCUS', parsed), serialized[0] + '\n')
AssertionError: 'LOCUS       NP_001832   360 aa      linear   PRI   18-DIC-2001\n' != 'LOCUS       NP_001832   360 aa      linear   PRI   18-DEC-2001\n'
- LOCUS       NP_001832   360 aa      linear   PRI   18-DIC-2001
?                                                        ^
+ LOCUS       NP_001832   360 aa      linear   PRI   18-DEC-2001
?                                                        ^


----------------------------------------------------------------------
```

**Comment by jairideout** [comment] 2016-02-03 22:38
Duplicate of #1153

**Closed by jairideout** 2016-02-03 22:38 UTC
