### ISSUE TITLE
Inheriting I/O from super classes

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1507] opened 2017-04-13 21:10 UTC
It would be awesome if I/O could be inherited from subclasses.  

For example, in gneiss, we are subclassing the `TreeNode` object in order to draw dendrograms.  When trying to save these objects to disk, we get the following error

```
---------------------------------------------------------------------------
UnrecognizedFormatError                   Traceback (most recent call last)
<ipython-input-23-7da78c6c9698> in <module>()
----> 1 lme_model.tree.write('../results/tree.nwk')
      2 for y in ynames:
      3     open('../results/%s_left' % y).write(','.join(list(tree.find(y).children[0].subset())))
      4     open('../results/%s_right' % y).write(','.join(list(tree.find(y).children[1].subset())))

/Users/mortonjt/miniconda3/envs/bio/lib/python3.5/site-packages/skbio/io/registry.py in write(self, file, format, **kwargs)
    671 
    672         def write(self, file, format=cls.default_write_format, **kwargs):
--> 673             return registry.write(self, into=file, format=format, **kwargs)
    674 
    675         imports = registry._import_paths(write_formats)

/Users/mortonjt/miniconda3/envs/bio/lib/python3.5/site-packages/skbio/io/registry.py in write(self, obj, format, into, **kwargs)
    615             raise UnrecognizedFormatError(
    616                 "Cannot write %r into %r, no %s writer found." %
--> 617                 (format, into, obj.__class__.__name__))
    618 
    619         writer(obj, into, **kwargs)

UnrecognizedFormatError: Cannot write 'newick' into '../results/tree.nwk', no UnrootedDendrogram writer found.
```

**Comment by ebolyen** [comment] 2017-04-13 22:47
:+1:, technically this is a duplicate of #1402. This is going to require deep changes to the IO registry, if anyone really wants to take this on, I could be of some limited assistance in describing how everything works in there.

**Closed by ebolyen** 2017-04-13 22:47 UTC
