### ISSUE TITLE
Cannot find `skbio.diversity`...

### ISSUE THREAD

**Issue by izaakm** [biocore/scikit-bio#1258] opened 2016-01-25 16:13 UTC
Does this module still exist? 

I recently installed scikit-bio with pip on OSX. I have never used scikit-bio before.

`dir(skbio)` returns the following: 

```
['DNA', 'DistanceMatrix', 'GeneticCode', 'OrdinationResults', 'Protein', 'RNA', 'Sequence', 'TabularMSA', 'TestRunner', 'TreeNode', '__all__', '__builtins__', '__credits__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_base', 'absolute_import', 'alignment', 'art', 'division', 'io', 'local_pairwise_align_ssw', 'motto', 'mottos', 'nj', 'print_function', 'read', 'sequence', 'skbio', 'stats', 'test', 'title', 'tree', 'util', 'write']
```

Running the test returns the following:

```
  $ python -m skbio.test
....................................................................................................................................................................................................................................................................................................................................................................S........................................................................................................................................................................................................................................................../usr/local/lib/python2.7/site-packages/skbio/util/_decorator.py:257: DeprecationWarning: copy is deprecated as of scikit-bio version 0.4.1, and will be removed in version 0.5.1. Use `copy.copy(seq)` instead of `seq.copy(deep=False)`, and `copy.deepcopy(seq)` instead of `seq.copy(deep=True)`.
  DeprecationWarning)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../usr/local/lib/python2.7/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)
........................F.....................F............................../usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:581: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._coords.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:582: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  subset_coords.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:584: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._metadata_map.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:585: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  subset_metadata_map.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:590: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._coords.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:591: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  subset_coords.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:593: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._metadata_map.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:594: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  subset_metadata_map.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:628: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._coords.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:629: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  exp_coords.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:637: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  bv._metadata_map.sort(axis=0),
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:638: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  exp_metadata_map.sort(axis=0))
.../usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:231: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  trajectory.sort(columns=0, inplace=True)
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:245: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  assert_data_frame_almost_equal(obs.sort(axis=0), exp.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:256: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  trajectory.sort(columns=0, inplace=True)
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:267: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  assert_data_frame_almost_equal(obs.sort(axis=0), exp.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:275: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  trajectory.sort(columns=0, inplace=True)
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:282: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  assert_data_frame_almost_equal(obs.sort(axis=0), exp.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:289: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  trajectory.sort(columns=0, inplace=True)
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:298: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  assert_data_frame_almost_equal(obs.sort(axis=0), exp.sort(axis=0))
/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_gradient.py:337: FutureWarning: sort(....) is deprecated, use sort_index(.....)
  assert_data_frame_almost_equal(obs.sort(axis=0), exp.sort(axis=0))
....................................../usr/local/lib/python2.7/site-packages/numpy/lib/utils.py:99: DeprecationWarning: `nanstd` is deprecated!
scipy.stats.nanstd is deprecated in scipy 0.15 in favour of numpy.nanstd.
Note that numpy.nanstd has a different signature.
  warnings.warn(depdoc, DeprecationWarning)
.........................................................................................................................................../usr/local/lib/python2.7/site-packages/skbio/util/_decorator.py:257: DeprecationWarning: f is deprecated as of scikit-bio version 0.1.0, and will be removed in version 0.1.4. You should now use skbio.g().
  DeprecationWarning)
....................................................................................................................................................
======================================================================
FAIL: test_ancom_alternative_test (skbio.stats.tests.test_composition.AncomTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_composition.py", line 630, in test_ancom_alternative_test
    assert_data_frame_almost_equal(result, exp)
  File "/usr/local/lib/python2.7/site-packages/skbio/util/_testing.py", line 1190, in assert_data_frame_almost_equal
    check_exact=False)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 946, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] are different

DataFrame.iloc[:, 0] values are different (100.0 %)
[left]:  [0, 0, 0, 0, 0, 0, 0]
[right]: [6, 6, 2, 2, 2, 2, 2]

======================================================================
FAIL: test_ancom_normal_data (skbio.stats.tests.test_composition.AncomTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/skbio/stats/tests/test_composition.py", line 643, in test_ancom_normal_data
    assert_data_frame_almost_equal(result, exp)
  File "/usr/local/lib/python2.7/site-packages/skbio/util/_testing.py", line 1190, in assert_data_frame_almost_equal
    check_exact=False)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 946, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/usr/local/lib/python2.7/site-packages/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] are different

DataFrame.iloc[:, 0] values are different (22.22222 %)
[left]:  [8, 7, 3, 3, 7, 3, 3, 3, 3]
[right]: [8, 8, 3, 3, 8, 3, 3, 3, 3]

----------------------------------------------------------------------
Ran 1791 tests in 45.979s

FAILED (SKIP=1, failures=2)
```

**Comment by ebolyen** [comment] 2016-01-25 18:41
Thanks for posting this @izaakm! `skbio.diversity` is still a part of scikit-bio, it's in fact just been updated with new phylogenetic metrics. The test failures strike me as a dependency conflict. Could you reply with the contents of `pip freeze`?

**Comment by izaakm** [comment] 2016-01-25 20:35
NP 

```
appnope==0.1.0
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
biom-format==2.1.5
biopython==1.66
bokeh==0.11.0
brewer2mpl==1.4.1
bz2file==0.98
CacheControl==0.11.6
certifi==2015.11.20.1
click==6.2
contextlib2==0.5.1
cycler==0.9.0
Cython==0.23.4
decorator==4.0.6
ExifRead==2.1.2
Flask==0.10.1
funcsigs==0.4
functools32==3.2.3.post2
future==0.15.2
futures==3.0.4
ggplot==0.6.8
gnureadline==6.3.3
h5py==2.5.0
httpretty==0.8.14
ipykernel==4.2.2
ipython==4.0.3
ipython-genutils==0.1.0
ipywidgets==4.1.1
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.1.0
jupyter-core==4.0.6
lockfile==0.12.2
Markdown==2.6.5
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.1
mock==1.3.0
natsort==4.0.4
nbconvert==4.1.0
nbformat==4.0.1
networkx==1.10
nose==1.3.7
notebook==4.1.0
numpy==1.10.4
pandas==0.17.1
path.py==8.1.2
patsy==0.4.1
pbr==1.8.1
pexpect==4.0.1
pickleshare==0.6
Pillow==3.1.0
plotly==1.9.5
prettytable==0.7.2
ptyprocess==0.5
Pygments==2.1
pylab==0.1.3
pyparsing==2.0.7
pyqi==0.3.2
python-dateutil==2.4.2
pytz==2015.7
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.1.1
requests==2.9.1
scikit-bio==0.4.1
scikit-image==0.11.3
scikit-learn==0.17
scipy==0.17.0
seaborn==0.7.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sklearn==0.0
statsmodels==0.6.1
sympy==0.7.6.1
terminado==0.6
tornado==4.3
traitlets==4.1.0
vboxapi==1.0
virtualenv==14.0.1
Werkzeug==0.11.3
wheel==0.26.0
xlrd==0.9.4
```

**Comment by jairideout** [comment] 2016-01-25 23:08
Thanks for the `pip freeze` output. I'm able to reproduce the test failures on OS X in Python 2 and 3. The tests pass with scipy 0.16.1 (available via `conda` and `pip`) but fail with scipy 0.17.0 (only available via `pip`). Looking into it further, will post back with more details.

@izaakm regarding `skbio.diversity`, does the following work for you?

```python
import skbio.diversity
```

The package may just be missing from `__all__` in `skbio/__init__.py` but should still be importable.

**Comment by jairideout** [comment] 2016-01-26 00:00
The two ANCOM tests are failing because something in `scipy.stats.mannwhitneyu` changed between scipy 0.16.1 and 0.17.0. Changing `test_ancom_alternative_test` to pass `alternative='less'` fixes the test. However, making the same change to `test_ancom_normal_data` doesn't fix the failure.

@mortonjt are you available to look into these ANCOM test failures?

**Comment by izaakm** [comment] 2016-01-26 00:07
Oops, I thought I had tried that... `import skbio.diversity` does work for me, thank you.

**Comment by mortonjt** [comment] 2016-01-26 02:48
I'll try to take a look at those tests this week.

**Comment by jairideout** [comment] 2016-01-26 16:21
Thanks!

**Comment by jairideout** [comment] 2016-01-26 16:30
Closing in favor of #1259 for tracking ANCOM unit test failures.

**Closed by jairideout** 2016-01-26 16:30 UTC
