### ISSUE TITLE
ancom zero values

### ISSUE THREAD

**Issue by antgonza** [biocore/scikit-bio#1372] opened 2016-06-07 00:28 UTC
ancom doesn't work with zero values. the current solution is to add 1 to all fields/features, should this be a default behavior as our data is sparse?

**Comment by mortonjt** [comment] 2016-06-07 00:33
I think this should also be a qiime2 specific feature, because there are many different types of pseudo count strategies out there.  Keeping that sort of logic separate in qiime2 imho would simplify the scikit-bio api.

**Comment by antgonza** [comment] 2016-06-07 00:35
Agree with this. However, not having the option in skbio means that all tools that use it will need to add this functionality: qiita, qiime2, others ...

**Comment by mortonjt** [comment] 2016-06-07 00:43
Not really.  We can develop these pseudo-count methods into skbio.  We already have two options readily available `multiplicative_replacement`, and the constant pseudocount.  

There are 2 reasons why I think it is OK keep the interface the way it is

1. Zeros are bad.  They actually mess up the results in ANCOM.  The more zeros.  The worse the results.  If the user actively accounts for this, they'll become aware of the problem.
2. The less branching logic that we have to account for here, the better.  I'm a bit leery of trying to guess the user's intentions based on their dataset.  Would we have to add `1` to their table if there happen to be zeros present?

**Comment by jairideout** [comment] 2016-06-07 16:15
👍 for the current interface. Since there's already many different ways to deal with zeros and it's an active area of research, keeping those replacement strategies separate from ANCOM will keep the method itself simple. We could always provide a convenience API to perform replacement *within* ANCOM in the future, but we'd still need the replacement API itself to exist (e.g., as it currently does, or as methods on `FeatureTable` in the future).

**Comment by gregcaporaso** [comment] 2016-06-08 18:47
Note that the authors mention adding a constant to values on the bottom of page 5 of the supplement (their omega value). They add 0.001, but note that some people may prefer to add 1.0. So, the pseudocount approach does seem to be recommended as a part of ANCOM, and I imagine it would be required to reproduce the data in the paper. @mortonjt, was that the case in your experience? Do you know if the R package does that?

**Comment by mortonjt** [comment] 2016-06-08 18:53
Yes, the R package adds 0.001 to all of their values.

The problem is they have multiple versions that add different
pseudo-counts.  Some versions have a pseudo-count of 1.
This is another reason why I don't think pseudo counts can be handled
internally.

**Comment by ebolyen** [comment] 2016-06-09 21:40
:+1: ideally we would have a mechanism in `FeatureTable` to just replace
values easily. Until then, vectors are really easy to mutate anyways. I
don't think there is a lot of benefit to baking this into ANCOM right now.

**Comment by mortonjt** [comment] 2017-02-04 05:56
Can we close this?  It looks like this has been resolved.

**Closed** 2018-09-20 22:58 UTC
