### ISSUE TITLE
TreeNode.read should not turn underscores into spaces in taxa names

### ISSUE THREAD

**Issue by ryneches** [biocore/scikit-bio#1225] opened 2015-12-09 10:56 UTC
For deeply silly reasons, it has become conventional in phylogenetics to represent spaces as underscores in taxa names (e.g., *Homo sapiens* would be `Homo_sapiens`). Owing to this historical blunder, one can make a good case that when displaying taxa names as labels in a figure, it is handy to automatically substitute spaces for underscores -- provided there is some way to suppress this behavior if the user really wants their underscores for some reason.

However, it does not make sense to perform this transformation on the representation of the data itself. Almost all conceivable use cases where a user would wish to access, manipulate or iterate over the taxa names require that they correspond **exactly** with the taxa names in other data structures. "Fixing" the underscores when reading a phylogeny breaks this correspondence, forcing the user to put the underscore back in whenever they make any sort of comparison to a table of metadata, to name one ubiquitous example.

I shudder to think how many person-hours people working on phylogenetic methods have wasted putting underscores into things and then taking them out again. I would greatly appreciate if scikit-bio were to opt out of this tawdry debacle and simply respect the names the user gives it. 

If the user's upstream tools create a tree with billions of taxa with names like `b_6?☹ snorkel #deadb33f Thursday////TOMATO|||肚臍`, scikit-bio should endeavor not to contribute to their abounding misery and frustration by cheerfully renaming everything. Or worse, just the ones that happen to have underscores...

**Comment by wasade** [comment] 2015-12-09 21:13
Does `convert_underscores=False` resolve your issue? The parameter is described toward the bottom [here](http://scikit-bio.org/docs/latest/generated/skbio.io.format.newick.html#module-skbio.io.format.newick). The parameter details are not readily available in the `TreeNode.read` docstring, which suggests it may make sense for the `read` methods of objects to have a means to access these documentation details included.

(cc @ebolyen regarding `read` parameters)

```python
13:05:48 (daniel@sandbar):~> t = TreeNode.read(StringIO("((a_1,b)x_,(c,d_2)e_4)root;"))
13:06:08 (daniel@sandbar):~> print(t.ascii_art())
                    /-a 1
          /x ------|
         |          \-b
-root----|
         |          /-c
          \e 4-----|
                    \-d 2

13:06:10 (daniel@sandbar):~> t = TreeNode.read(StringIO("((a_1,b)x_,(c,d_2)e_4)root;"), convert_underscores=False)

13:06:20 (daniel@sandbar):~> print(t.ascii_art())
                    /-a_1
          /x_------|
         |          \-b
-root----|
         |          /-c
          \e_4-----|
                    \-d_2
```

**Comment by ryneches** [comment] 2015-12-09 22:11
Ah ha! Indeed it does. I think was expecting `.read()` to call the Newick parser, so I wasn't expecting to have to follow the breadcrumbs into the parser to find accessible parameters in `.read()`. 

Curiously, it actually appears that the underscores only get replaced when you convert the tree into something else. If you iterate over `.tips()` and print them, you always see the underscores regardless of the state of `convert_underscores`. However, if you create a distance matrix with `.tip_tip_distances()`, then `convert_underscores` does indeed have an effect. Ditto for `.ascii_art()`.

It looks like TreeNode actually does behave the way I suggested; it leaves the underscores alone in its internal representation of the data, and `convert_underscores` is applied as a parameter controlling how trees are displayed. It's just weird that a `DistanceMatrix` would be treated as a display.

Wouldn't it be more logical for `convert_underscores` to be a parameter of `.ascii_art()` instead of `.read()`? Or maybe it should be something the user can toggle explicitly, instead of as a side effect of I/O?

**Comment by wasade** [comment] 2015-12-10 00:19
`read` does call the Newick parser, but via the io registry system and the aptly named [`monkey_patch`](https://github.com/biocore/scikit-bio/blob/master/skbio/io/registry.py#L595) method. 

I'm not able to reproduce this behavior w.r.t. the differential behavior of `convert_underscores`, or perhaps I'm misunderstanding. Can you provide an example please?

```python
16:11:41 (daniel@sandbar):~> t = skbio.TreeNode.read(io.StringIO('(a_1,b_2)root;'))

16:11:54 (daniel@sandbar):~> print(t.ascii_art())
          /-a 1
-root----|
          \-b 2

16:11:56 (daniel@sandbar):~> for n in t.traverse():
   ....:     print(n.name)
   ....:
root
a 1
b 2

16:12:03 (daniel@sandbar):~> for n in t.tips():
    print(n.name)
   ....:
a 1
b 2

16:12:10 (daniel@sandbar):~> t = skbio.TreeNode.read(io.StringIO('(a_1,b_2)root;'), convert_underscores=False)

16:12:20 (daniel@sandbar):~> print(t.ascii_art())                                                           /-a_1
-root----|
          \-b_2

16:12:23 (daniel@sandbar):~> for n in t.traverse():                                                     print(n.name)
   ....:
root
a_1
b_2

16:12:26 (daniel@sandbar):~> for n in t.tips():                                                         print(n.name)
   ....:
a_1
b_2

16:12:30 (daniel@sandbar):~> t.children[0].name
Out[21]: 'a_1'
```

**Comment by ryneches** [comment] 2015-12-10 01:30
Sure. Here's the particular behavior that brought this to my attention in the first place :

```python
t = TreeNode.read(io.StringIO(u"((a_1:1,b:2)x_:3,(c:4,d_2:5)e_4:6)root;"), convert_underscores=True)
for tip in t.tips() :
    print tip
print t.tip_tip_distances().ids
```
produces the following output :
```
a_1:1.0;
b:2.0;
c:4.0;
d_2:5.0;
(u'a 1', u'b', u'c', u'd 2')
```
Note the underscores are still there, presumably as a result of the automatic invocation of `tip.__str__()`. In your example, you are invoking `tip.name.__str__()`, which produces a different result for some reason. 

Then, we go ahead and suppress the underscore conversion...
```python
t = TreeNode.read(io.StringIO(u"((a_1:1,b:2)x_:3,(c:4,d_2:5)e_4:6)root;"), convert_underscores=False)
for tip in t.tips() :
    print tip
print t.tip_tip_distances().ids
```
Which yields :
```
'a_1':1.0;
b:2.0;
c:4.0;
'd_2':5.0;
(u'a_1', u'b', u'c', u'd_2')
```
Huh.

**Comment by ebolyen** [comment] 2015-12-21 22:02
@ryneches When you iterate over the tips, each tip is it's own `TreeNode` and is then serialized as `newick` using the current defaults (using `str` implicitly as you pointed out). When you access the `name` property directly that is the *actual* object model for the node name. This property is what is used as an `id` when creating a `DistanceMatrix` via `tip_tip_distances`.

In other words, your example is actually working completely correctly, it is only the implicit call to `str` which is reconverting spaces into underscores. (You might also notice when this happens you end up with a valid newick string with the `label:distance;` instead of just `label`)

Basically scikit-bio will preserve the information as best as it can using the afore-mentioned conventions.

If your `node.name` == `something_like_this` -> newick == `'something_like_this'` (Notice the escaping string. If we left this alone a different program could reasonably interpret it as `something like this` which is NOT `something_like_this`)
If your `node.name` == `something like this` -> newick == `something_like_this` (No escape string because of the convention)
If your `node.name` == `Crazy; stuff; here (foobar)` -> newick == `'Crazy; stuff; here (foobar)'` (Just like the first example, `;` ` ` and `()` are newick operators and are escaped with `'`)
If your `node.name` == `'uh oh'` -> newick == `''uh_oh''` (This is an edge case of our implementation, nothing wrong with it, but a different valid encoding would have been `'''uh oh'''`)

If it is reading newick == `something_like_this` -> `node.name` == `something like this` (See how they are roundtrippable)
If it is reading newick == `something like this` -> Error as labels cannot have spaces in them
If it is reading newick == `'something like this'` -> `node.name` == `something like this`

Overall I completely agree with your first post that this convention is horrible, **but** if we were to ignore it then we would be subtly incompatible with other tools. There are also a **lot** of edge cases to consider with newick, so if we were to change this, we would need to do so in a way that would require user-clarification (which is essentially what `convert_underscores` is) or would otherwise fail so as to avoid incorrect interpretation.

@wasade At this time we don't have a great way to document read parameters automagically as `read` and `write` are methods decorated onto classes at import time once the registry is known. It would be super cool if there was a clean way to do this though. (I don't think having the parameters available in the function prototype is necessarily a good idea either (think scipy pdist), not sure if that was what you were suggesting)

I'm going to close this for now as our current position is to match whatever (few though there are) specifications/conventions may exist and to **never** produce a file which does not at least meet those specifications.

**Closed by ebolyen** 2015-12-21 22:02 UTC
