### ISSUE TITLE
Importing QIIME module, scikit-bio unicode error

### ISSUE THREAD

**Issue by DidemnumVex** [biocore/scikit-bio#1502] opened 2017-03-02 01:03 UTC
Ok, I've been asked by @jairideout to bring this issue here from [SO](http://stackoverflow.com/questions/42427570/importing-qiime-script-as-module-error-importing-from-skbio?noredirect=1#comment72121835_42427570).  
Background: I have many folders and directories that I'm processing through QIIME.  I've set a Python script that pulls plate & well data from MySQL and points it to a Fastq....while doing some other processing.
Because I have so many files (hundreds which will be split into tens of thousands), I'd like to import split_libraries.py as a module and then potentially run it in parallel, since I have 64 cores on my server (I'm not there yet).
I get hung up on 
`import split_libraries_fastq`
Which gives the following error:
`~ENVTC/lib/python2.7/site-packages/skbio/alignment/_ssw_wrapper.so: undefined symbol: PyUnicodeUCS2_Format`
Which seems like it could be solvable with some formatting adjustments?
Once I'm there, I'm not sure how to deal with the options, because it looks like there is a different make_option module than the sys.argv that I usually use.  
I have a workaround for now, which is to use os.sys and run it as if it were on the command line, but that seems inefficient, doesn't show error messages (if there are any), and I don't know if I'll be able to run in parallel using os, so I'd like to know how to import the script properly.

Thanks for your patience.  
Below is my sys config.
I have Qiime1 , running on CentOS, with Python 2.7.  Spyder is my IDE, running on a different python, still 2.7.
from print_qiime_config:

>  QIIME library version:	1.9.1  
>     QIIME script version:	1.9.1
> qiime-default-reference version:	0.1.3
>                   NumPy version:	1.9.1
>                   SciPy version:	0.15.1
>                  pandas version:	0.16.2
>              matplotlib version:	1.4.3
>             biom-format version:	2.1.4
>                    h5py version:	Not installed.
>                    qcli version:	0.1.1
>                    pyqi version:	0.3.2
>              scikit-bio version:	0.2.3
>                  PyNAST version:	1.2.2
>                 Emperor version:	0.9.51
>                 burrito version:	0.9.1
>        burrito-fillings version:	0.1.1
>               sortmerna version:	SortMeRNA version 2.0, 29/11/2014
>               sumaclust version:	SUMACLUST Version 1.0.00
>                   swarm version:	Swarm 1.2.19 [Jul 22 2015 10:10:55]
>                           gdata:	Installed.

**Comment by jairideout** [comment] 2017-03-02 19:55
How did you install scikit-bio? Are you on a 64-bit system?

Much of what you're doing is specific to QIIME 1 (e.g. importing a QIIME 1 script as a library). We can help you with your scikit-bio installation issue (the SSW wrapper error) but I recommend posting QIIME 1-specific questions on the [QIIME 1 forum](http://forum.qiime.org).

**Comment by DidemnumVex** [comment] 2017-03-02 20:09
I installed scikit-bio as part of QIIME 1, I think.  If not that, then PIP (it's been a while).  Yes, I'm on a 64 bit system.
I guess I thought using SO would get me help since this really doesn't seem to be an install issue.  The scikit-bio works with the QIIME script when I run through the command line.  I'm just really trying to work the QIIME script into a larger pipeline and it doesn't import into my script correctly.  I'm posting here because you asked me to on SO, and the scikit-bio appears to be where the hangup is.  So again, the package appears to work fine for normal purposes.  I'm trying to incorporate it into my program so that I can process my mountains of data.  But I can't get past the import step.

**Comment by jairideout** [comment] 2017-03-06 16:43
You are welcome to await support on [your SO question](http://stackoverflow.com/q/42427570/3776794), but I don't know if you'll get additional help there. I requested that you move your question here because we will end up polluting your SO question with a bunch of comments -- it's going to require some back-and-forth to identify the issue, thus it's not the best place to work out on SO.

I recommend creating a new conda environment and installing the latest version of scikit-bio within that environment. There's instructions on [scikit-bio.org](http://scikit-bio.org) for doing that. Please post the conda command(s) you ran and the output produced from those commands if you're still receiving errors when using scikit-bio.

Once we've determined what the issue is we can look at your QIIME 1 install and how scikit-bio is interacting with that. I may refer you to the QIIME 1 forum at that point, since scikit-bio and QIIME 1 are different software projects.

**Comment by DidemnumVex** [comment] 2017-03-07 00:40
Thanks, @jairideout .  I'm getting some help from the [QIIME1 forum](https://groups.google.com/d/msg/qiime-forum/ruVVccTgDoQ/YZSH7CDgDQAJ).  Today I discovered that if I don't use spyder, but the command line python, the scripts import without error (I haven't tested them on data yet).  I did have my spyder path pointed at the same python that I was using in my command line.

**Comment by jairideout** [comment] 2017-03-07 18:12
Glad you're getting help on the QIIME 1 forum! I haven't used Spyder so I don't have ideas offhand for what would be causing it to use a different Python executable. It sounds like it's an IDE/environment issue potentially unrelated to scikit-bio, so I'll close this issue. If you find anything that needs fixing within scikit-bio to provide better integration with Spyder, please feel free to reopen the issue. Thanks!

**Closed by jairideout** 2017-03-07 18:12 UTC
