### ISSUE TITLE
docs don't build with new Sphinx release (1.2.3)

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#661] opened 2014-09-04 05:42 UTC
The docs don't build with the newest Sphinx (1.2.3) that was released a couple of days ago. Here's the warning message (which gets promoted to an error):

```
Warning, treated as error:
/Users/jairideout/dev/scikit-bio/doc/source/diversity.rst:15: WARNING: "::" in automodule name doesn't make sense
```

When I downgraded to 1.2.2, the issue went away.

A quick look through their changelog and some googling hasn't helped much. Would be good to get this fixed before the next release.

**Comment by mortonjt** [comment] 2015-02-23 03:23
Looks like this issue has been around for a while.  Maybe it would be appropriate to ask some of the sphinx developers on their mailing list?

**Comment by Jorge-C** [comment] 2015-02-23 04:22
:+1:

**Comment by anderspitman** [comment] 2015-02-23 05:45
[Fixed in latest Sphinx possibly?](https://github.com/sphinx-doc/sphinx/issues/1585)

**Comment by jairideout** [comment] 2015-02-23 18:12
Just tried the latest Sphinx (1.3b3dev-20150223) and got a different error:

```
/Users/jairideout/dev/scikit-bio/doc/source/generated/generated/skbio.diversity.alpha.ace.rst:: WARNING: document isn't included in any toctree
```

**Comment by Jorge-C** [comment] 2015-02-23 18:16
Is that a legitimate error or spurious?

**Comment by jairideout** [comment] 2015-02-23 18:20
Not sure how much this particular warning matters to the correctness of the docs. We have Sphinx warnings promoted to errors because it's caught other (legitimate) doc problems in the past. I'm able to reproduce it each time I run `make html` so it doesn't seem like a random error. Sorry if I misread your question!

**Comment by ebolyen** [comment] 2015-09-10 17:10
Our docs work again on the current master of Sphinx. This was a regression that was fixed in https://github.com/sphinx-doc/sphinx/pull/1892. So whenever `1.3.2` lands we will be in good shape!

Alternatively, we are starting to heavily modify the `autosummary` extension, so just writing our own extension would also fix this (and give us more power to fix future regressions).

**Closed** 2015-11-09 23:11 UTC
Labels: documentation, maintenance
