### ISSUE TITLE
AttributeError: 'F_onewayResult' object has no attribute 'shape' with numpy 1.12

### ISSUE THREAD

**Issue by sandrotosi** [biocore/scikit-bio#1471] opened 2016-12-21 00:15 UTC
Hello,
in debian numpy 1.12 has been uploaded and it causes scikit-bio v0.5.1 tests to fail:

```
>     multiple_comparisons_correction=None)
>   File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/skbio/stats/composition.py", line 971, in ancom
>     _logratio_mat = _log_compare(mat.values, cats.values, significance_test)
>   File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/skbio/stats/composition.py", line 1084, in _log_compare
>     arr=ratio)
>   File "/usr/lib/python3/dist-packages/numpy/lib/shape_base.py", line 133, in apply_along_axis
>     if res.shape == ():
> AttributeError: 'F_onewayResult' object has no attribute 'shape'
```

(full log and additional refs at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848758)

could you please have a look? thanks!

**Comment by kdmurray91** [comment] 2016-12-22 02:27
Note that fixing this is urgent, as it will stop skbio being in the next Debian release. I will work on this from the debian side if I have time, but that is unlikely.

**Comment by mortonjt** [comment] 2016-12-22 02:38
Yeah ... that is coming from the new named tuples in scikit-bio.  That's annoying :/

**Comment by kdmurray91** [comment] 2016-12-22 02:46
@mortonjt Any ideas for a quick fix? We are able to cherry-pick a fix over from master as a debian patch by the way, so there's no need for a release (though one might be needed in any case). Let me know if you need a hand with fixing this.

**Comment by mortonjt** [comment] 2016-12-22 03:09
The fix should actually be pretty easy - we can probably fix the input lambda function.  Let me push in a PR.

**Comment by kdmurray91** [comment] 2016-12-22 09:13
@mortonjt Close, but no cigar. I've built with that commit cherry-picked over as a patch, but I get the following:

```
======================================================================   
ERROR: test_ancom_basic_counts_swapped (skbio.stats.tests.test_composition.AncomTests)
---------------------------------------------------------------------- 
Traceback (most recent call last):                                     
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/tests/test_composition.py", line 920, in test_ancom_basic_counts_swapped
    result = ancom(self.table8, self.cats8)                                                                                         
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/composition.py", line 977, in ancom
    1, logratio_mat)                                                                                          
  File "/usr/lib/python3/dist-packages/numpy/lib/shape_base.py", line 133, in apply_along_axis
    if res.shape == ():                                                                       
AttributeError: 'list' object has no attribute 'shape'
                                                      
======================================================================
ERROR: test_ancom_multiple_comparisons (skbio.stats.tests.test_composition.AncomTests)
----------------------------------------------------------------------
Traceback (most recent call last):                  
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/tests/test_composition.py", line 888, in test_ancom_multiple_comparisons
    significance_test=scipy.stats.mannwhitneyu)                                                                                                      
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/composition.py", line 977, in ancom
    1, logratio_mat)                                             
  File "/usr/lib/python3/dist-packages/numpy/lib/shape_base.py", line 133, in apply_along_axis
    if res.shape == ():                                   
AttributeError: 'list' object has no attribute 'shape'
                             
======================================================================
ERROR: test_ancom_multiple_groups (skbio.stats.tests.test_composition.AncomTests)
----------------------------------------------------------------------
Traceback (most recent call last):                                            
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/tests/test_composition.py", line 839, in test_ancom_multiple_groups
    result = ancom(test_table, test_cats)     
  File "/build/python-skbio-0.5.1/.pybuild/pythonX.Y_3.5/build/skbio/stats/composition.py", line 977, in ancom
    1, logratio_mat)                       
  File "/usr/lib/python3/dist-packages/numpy/lib/shape_base.py", line 133, in apply_along_axis
    if res.shape == ():                                                                         
AttributeError: 'list' object has no attribute 'shape'                                    
                                                                                
```

**Comment by jairideout** [comment] 2016-12-22 17:31
@mortonjt, to fix this in scikit-bio there's a couple options:

- bump the minimum required scipy version in setup.py and get the code working with that, OR: 
- update the code to work with both old and new scipy versions (no setup.py scipy version bump necessary)

**Comment by kdmurray91** [comment] 2016-12-22 21:07
From Debian's end, we package with whatever version of scipy/numpy that is in Debian. Therefore, strictly requiring a specific version in setup.py has no effect for us. @jairideout's second option is the only feasible one for debian, unfortunately.

**Comment by mortonjt** [comment] 2016-12-22 23:53
@kdmurray91 - it looks like the original error has been fixed.  We just need to swap out the other `np.apply_along_axis`.  Will send correction in a few minutes.  Thanks for testing this out!!

**Comment by kdmurray91** [comment] 2016-12-24 07:19
Whoohoo! #1472 seems to fix the build on my laptop. Will push an update with that PR added in as a patch.

**Comment by kdmurray91** [comment] 2016-12-24 10:54
Happy to say that the package has been uploaded, and the release-critical bugs closed. Hopefully we'll see scikit-bio in Debian 9. :)

**Comment by mortonjt** [comment] 2016-12-24 17:02
Thanks!

**Comment by jairideout** [comment] 2017-10-06 18:34
Closing as I wasn't able to reproduce this locally with numpy 1.12. I think the packages upstream have been fixed since the issue was originally reported. If this is still an issue please reopen, thanks!

**Closed by jairideout** 2017-10-06 18:34 UTC
