### ISSUE TITLE
Debian documentation build error

### ISSUE THREAD

**Issue by kdmurray91** [biocore/scikit-bio#1283] opened 2016-02-17 22:09 UTC
Hi @ebolyen @jairideout,

Here is the doc build error I spoke of on gitter. Turns out that it doesn't kill the build even with that patch disabled, which is strange.

```
/build/python-skbio-0.4.1/.pybuild/pythonX.Y_2.7/build/skbio/diversity/__init__.py:docstring of skbio.diversity:172: WARNING: Exception occurred in plotting diversity-1
 from /build/python-skbio-0.4.1/doc/source/diversity.rst:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 30, in <module>
TypeError: initial_value must be unicode or None, not str
/build/python-skbio-0.4.1/doc/source/diversity.rst:461: WARNING: Exception occurred in plotting diversity-2
 from /build/python-skbio-0.4.1/doc/source/diversity.rst:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 9, in <module>
NameError: name 'wu_pc' is not defined
/build/python-skbio-0.4.1/doc/source/diversity.rst:509: WARNING: Exception occurred in plotting diversity-3
 from /build/python-skbio-0.4.1/doc/source/diversity.rst:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 11, in <module>
NameError: name 'wu_dm' is not defined
```

Cheers,
K

**Comment by ebolyen** [comment] 2016-02-17 22:13
Are you running the doc build in Python 3 or 2? This error looks like it is caused by `io.StringIO` which will work fine in Py3 as string literals are unicode, but will make Python 2 all upset.

**Comment by ebolyen** [comment] 2016-02-17 22:13
Basically our docs only build in Python 3.

**Comment by kdmurray91** [comment] 2016-02-17 22:13
Hmm. that could be it

**Comment by kdmurray91** [comment] 2016-02-17 22:14
I'll see if I can force a python3 build

**Comment by ebolyen** [comment] 2016-02-17 22:14
Thanks @kdmurray91!

**Comment by jairideout** [comment] 2016-02-17 23:27
Closing since this ended up being a Python 2 issue (see gitter).

**Closed by jairideout** 2016-02-17 23:27 UTC
